# Generated by Django 5.2.5 on 2025-12-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_alter_chat_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='created_at',
        ),
    ]
