# Generated by Django 5.2.5 on 2025-12-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chat_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, default='Unnamed Chat', max_length=255),
            preserve_default=False,
        ),
    ]
