# Generated by Django 5.2.5 on 2025-12-23 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0002_remove_groupchat_members_groupmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='joined_at',
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
