# Generated by Django 5.2.5 on 2025-12-23 01:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def remove_duplicate_groupchat_names(apps, schema_editor):
    GroupChat = apps.get_model('groupchat', 'GroupChat')
    duplicates = GroupChat.objects.values('name').annotate(count=models.Count('id')).filter(count__gt=1)
    for duplicate in duplicates:
        name = duplicate['name']
        groupchats = GroupChat.objects.filter(name=name).order_by('id')
        # Keep the first one, delete the rest
        for groupchat in groupchats[1:]:
            groupchat.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0003_remove_groupmember_joined_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_groupchat_names,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RenameField(
            model_name='groupmessage',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('user', 'group')},
        ),
        migrations.AddField(
            model_name='groupchat',
            name='members',
            field=models.ManyToManyField(related_name='group_chats', through='groupchat.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupchat.groupchat'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='is_admin',
        ),
    ]
