# Generated by Django 5.2.5 on 2025-12-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0004_rename_content_groupmessage_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
