# Generated by Django 5.2.5 on 2025-12-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0005_alter_groupchat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
