# Generated by Django 5.2.5 on 2025-12-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0008_alter_groupmember_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='name',
            field=models.CharField(default='unknowncht', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
