# Generated by Django 5.2.5 on 2025-12-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0010_rename_text_groupmessage_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
